version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:latest
    working_directory: ~/mos-connection
    steps:
      - checkout
      - attach_workspace:
          at: ~/mos-connection
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}
            - yarn-cache-
      - run: yarn install
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .
  check_vulnerabilities:
    docker:
      - image: circleci/node:latest
    working_directory: ~/mos-connection
    steps:
      - attach_workspace:
          at: ~/mos-connection
      - run: yarn install
      - run: |
            if [ "${CIRCLE_BRANCH}" == "production" ]; then
              yarn validate:dependencies
            else
              yarn validate:dependencies || true
            fi
  test_and_report:
    docker:
      - image: circleci/node:latest
    working_directory: ~/mos-connection
    steps:
      - attach_workspace:
          at: ~/mos-connection
      - run: yarn install
      - run: yarn ci
      - run: yarn send-coverage
      - store_artifacts:
          path: ./coverage/clover.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: ./coverage/clover.xml
  test_node-6:
    docker:
      - image: circleci/node:6
    working_directory: ~/mos-connection
    steps:
      - attach_workspace:
          at: ~/mos-connection
      - run: yarn install
      - run: yarn ci
      # - run: yarn send-coverage
      # - store_artifacts:
      #     path: ./coverage/clover.xml
      #     prefix: tests
      # - store_artifacts:
      #     path: coverage
      #     prefix: coverage
      # - store_test_results:
      #     path: ./coverage/clover.xml
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/mos-connection
    steps:
      - attach_workspace:
          at: ~/mos-connection
      - run: yarn install
      - run: yarn build
          # name: yarn build
          # command: |
          #   if [ "${CIRCLE_BRANCH}" == "production" ]; then
          #     CI=true PUBLIC_URL=https://mos-connection-production.now.sh yarn build
          #   elif [ "${CIRCLE_BRANCH}" == "development" ]; then
          #     CI=true PUBLIC_URL=https://mos-connection-alpha.now.sh yarn build
          #   elif [ "${CIRCLE_BRANCH}" == "master" ]; then
          #     CI=true PUBLIC_URL=https://mos-connection-beta.now.sh yarn build
          #   else
          #     echo "This failed miserably!"
          #   fi
      - persist_to_workspace:
          root: .
          paths: .
  # Some kind of serverless-deployment. Will update with npm/yarn deployment later
  # deployment:
  #   docker:
  #     - image: circleci/node:latest
  #   working_directory: ~/mos-connection
  #   steps:
  #     - attach_workspace:
  #         at: ~/mos-connection
  #     - run: yarn install
  #     - run: sudo yarn global add now
  #     - deploy:
  #         name: Deploy & Alias.
  #         command: |
  #           if [ "${CIRCLE_BRANCH}" == "production" ]; then
  #             now build -t ${NOW_TOKEN} -n=mos-connection --static
  #             now -t ${NOW_TOKEN} alias mos-connection-production.now.sh
  #           elif [ "${CIRCLE_BRANCH}" == "development" ]; then
  #             now build -t ${NOW_TOKEN} -n=mos-connection --static
  #             now -t ${NOW_TOKEN} alias mos-connection-alpha.now.sh
  #           elif [ "${CIRCLE_BRANCH}" == "master" ]; then
  #             now build -t ${NOW_TOKEN} -n=mos-connection --static
  #             now -t ${NOW_TOKEN} alias mos-connection-beta.now.sh
  #           else
  #             echo "This failed miserably!"
  #           fi
workflows:
  version: 2
  test_build_deploy:
    jobs:
      - checkout_code
      - check_vulnerabilities:
          requires:
            - checkout_code
      - test_and_report:
          requires:
            - checkout_code
      - test_node-6:
          requires:
            - checkout_code
      - build:
          requires:
            - checkout_code
          filters:
            branches:
              only:
                - development
                - master
                - production
      # - deployment:
      #     requires:
      #       - check_vulnerabilities
      #       - test_and_report
      #       - build
      #     filters:
      #       branches:
      #         only:
      #           - development
      #           - master
      #           - production
